spring.application.name=data-pipeline
spring.profiles.active=dev
tags.whitelist.path=classpath:config/allowed-tags.json

#server.port=8081
server.port=${DATA_PIPELINE_PORT:8081}

# Google
#google.sheets.spreadsheet-id=1n-Vt71uIq93xS1KiDqi1j6mljuKpO0dtlFsIyI34Auk
#google.sheets.export-sheet-name=Test

google.sheets.spreadsheet-id=${GOOGLE_SHEETS_SPREADSHEET_ID}
google.sheets.export-sheet-name=${GOOGLE_SHEETS_EXPORT_SHEET_NAME}


# Spoonacular
#spoonacular.base-url=api.spoonacular.com
#spoonacular.api-key=978f93d8b86143f1817b9cbd1c743ee5
#spoonacular.source=spoonacular

spoonacular.base-url=${SPOONACULAR_BASE_URL}
spoonacular.api-key=${SPOONACULAR_API_KEY}
spoonacular.source=${SPOONACULAR_SOURCE}


logging.level.org.springframework.web.reactive.function.client=DEBUG

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/nutrition_data
#spring.datasource.username=nutrition_pipeline
#spring.datasource.password=pipeline

spring.datasource.url=jdbc:postgresql://${SOURCE_DB_HOST}:5432/${SOURCE_NAME}
spring.datasource.username=${SOURCE_USERNAME}
spring.datasource.password=${SOURCE_PASSWORD}




#Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# === Liquibase ===
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=dev
spring.liquibase.clear-checksums=true
spring.liquibase.default-schema=public
spring.liquibase.drop-first=false
