#server.port=8080
server.port=${BACKEND_PORT:8080}
#debug=true

#Hidden
spring.mvc.hiddenmethod.filter.enabled=true


#TEST########
# PostgreSQL (Test Data Source)
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.username=testuser
#spring.datasource.password=testpass

#spring.datasource.url=jdbc:postgresql://${NUTRI_DB_HOST}:${NUTRI_PORT}/${NUTRI_NAME}
spring.datasource.url=jdbc:postgresql://${NUTRI_DB_HOST}:5432/${NUTRI_NAME}
spring.datasource.username=${NUTRI_USERNAME}
spring.datasource.password=${NUTRI_PASSWORD}

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.contexts=test
spring.liquibase.change-log=classpath:db/changelog/db.changelog-test.xml

#Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
logging.level.io.nutritionApp.converter=DEBUG.
#spring.jpa.properties.hibernate.show_sql=true

# SQL-Query
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
